domain: INFRA
type: REDIS
identifier: targetName
name: targetName

conditions:
  - attribute: metricName
    prefix: redis_

tags:
  - clusterName
  - targetName

compositeMetrics:
  goldenMetrics: ./golden_metrics.yml
  summaryMetrics: ./summary_metrics.yml
